### ISSUE TITLE
v0.4.1 not available in the Arduino Library Manager

### ISSUE THREAD

**Issue by arnogramatke** [luni64/TeensyTimerTool#18]
Hi,

the last release of the TeensyTimerTool that I can see in the Arduino Library Manager is v.0.4.0.

It looks like the order of tagging v0.4.1 and updating the library.json was mixed up. Would be great to have v0.4.1 available in the Library Manager.

Thanks
Arno

<img width="825" alt="Arduino Library Manager" src="https://user-images.githubusercontent.com/27431532/153615250-909d46ad-e199-4a81-83a2-58a8b2ff7c9e.png">

**Comment by luni64** [comment]
Updated to 0.4.3. Lets hope this time the syncing works as expected

**Comment by luni64** [comment]
Is updated: 
![image](https://user-images.githubusercontent.com/12611497/153638045-1bf8b2a1-cc4f-46c6-832e-5c5b445a6d96.png)
