### ISSUE TITLE
Tick timer not working on Teensy LC

### ISSUE THREAD

**Issue by RocketManRC** [luni64/TeensyTimerTool#2]
I really like the idea of this library and for my application the tick timer will be perfect. Unless I am doing something wrong I don't think it works on the Teency LC and I believe it is because ARM_DWT_CYCCNT is always 0 on that processor. To test I am using the example HelloOneShot.

Cheers!

**Comment by luni64** [comment]
That's true, I started working around that a couple of days ago but didn't find time yet. In case you want to experiment, the systick counter might help: https://forum.pjrc.com/threads/28407-Teensyduino-access-to-counting-cpu-cycles?p=116317&viewfull=1#post116317
might do the trick

**Comment by RocketManRC** [comment]
Yes I already use that counter directly in my application. It is only 16 bits so I don't think that will work in your library will it? I think you could just use micros() in your library for the Teensy LC and that would at least get it working. It would do the job for me at least.

I'm regretting using the Teensy LC but I had a few of them kicking around. That's never the best way to choose a microcontroller for a project :-)

**Comment by luni64** [comment]
>Yes I already use that counter directly in my application. It is only 16 bits so I don't think that will work in your library will it? 

Sure, but extending to 32bit should not be too difficult...

> I think you could just use micros() in your library for the Teensy LC and that would at least get it working. It would do the job for me at least.

Good idea for a quick fix. Implemented and uploaded it. Can you give it a try?

>I'm regretting using the Teensy LC but I had a few of them kicking around. That's never the best way to choose a microcontroller for a project :-)

Why not? At least it triggered me fixing the issue :-)

**Comment by RocketManRC** [comment]
That works great now and makes my code a lot cleaner and easier to understand. I can see that your library would be really beneficial once you need several timers and different types of timers. Very cool!

Thanks!
