### ISSUE TITLE
Protect unsafe usage of `BaseTimer::start` and `BaseTimer::stop`

### ISSUE THREAD

**Issue by korhadris** [luni64/TeensyTimerTool#7]
I know I shouldn't be doing this, but I noticed that `BaseTimer::start` and `BaseTimer::stop` use the `timerChannel` pointer without checking them; I would expect them to return `errorCode::notInitialized` if it isn't set yet.

Test to reproduce crashes:
```c++
#include <TeensyTimerTool.h>

TeensyTimerTool::PeriodicTimer t1;

void begin() {
  t1.start();  // Dies here without progressing (expected seg fault)
  // Rest of code
}
```

**Comment by korhadris** [comment]
I don't mind making a PR for this change if wanted too...

**Comment by luni64** [comment]
Thanks for spotting this. I'll fix it later today

**Comment by luni64** [comment]
Done in https://github.com/luni64/TeensyTimerTool/commit/7eab51926f3d5ef96103bef7fd1741c6f6b7415f
