### ISSUE TITLE
Timer is not Accurate in 0.3.2 release

### ISSUE THREAD

**Issue by iharshadec** [luni64/TeensyTimerTool#9]
@luni64 @lunOptics 
HW:- Teensy 4.0
I was using 0.1.10 Release till date and today I updated to 0.3.2 release.
I see that my code is not working anymore. Here is the example that I was using earlier.
I have this code working with correct timing on 0.1.10 Release + 600/528/150 Mhz

Instead of 10mSec I am gettting this function called at every 1.5uSec Approx.
![image](https://user-images.githubusercontent.com/20681096/107511030-ee450a80-6bca-11eb-9d56-215c5bd86821.png)

```
/********************************************************
 * Basic usage of the timer
 * 
 * Generates a timer from the timer pool and
 * starts it with a period of 250ms. 
 * The timer callback simply toggles the built in LED
 * 
 ********************************************************/

#include "TeensyTimerTool.h"

using namespace TeensyTimerTool;
PeriodicTimer t1(PIT);

void vStartTimer()
{
  t1.begin(callback, 10'000); //10mSec
}

void vStopTimer()
{
  t1.begin([] {}, 10'000); //10mSec  
}

void callback()
{
    digitalWriteFast(LED_BUILTIN, !digitalReadFast(LED_BUILTIN));    
}

void setup()
{
    pinMode(LED_BUILTIN,OUTPUT);   
    vStartTimer();
}

void loop()
{   
}
```

**Comment by luni64** [comment]
Sorry for the delayed answer. I tested your code and it works nicely. 
![image](https://user-images.githubusercontent.com/12611497/110235599-41dc1700-7f31-11eb-97fe-5f713f5b4ae3.png)

Do you still have this issue?
